---
version: "3.5"

services:
  #nginx:
  #  #image: nginx:latest
  #  build:
  #    context: ./nginx/
  #  container_name: nginx
  #  # depends_on:
  #  #   - flask
  #  #volumes:
  #  #  - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #  networks:
  #    - nbi-net
  #  ports:
  #    - 80:80

  keystone:
    container_name: keystone
    build:
      context: ./keystone/
      args:
        KEYSTONE_DB_PASSWORD: ${KEYSTONE_DB_PASSWORD}
        KEYSTONE_DB_HOST: ${KEYSTONE_DB_HOST:-"database"}
        KEYSTONE_ADMIN_PASSWORD: ${KEYSTONE_ADMIN_PASSWORD}
        HTTP: ${HTTP:-http}
    depends_on:
      - database
    networks:
      - keystone-net
    env_file:
    - ./keystone/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      KEYSTONE_ADMIN_PASSWORD: ${KEYSTONE_ADMIN_PASSWORD}
      KEYSTONE_DB_PASSWORD: ${KEYSTONE_DB_PASSWORD}
      KEYSTONE_DB_HOST: ${KEYSTONE_DB_HOST:-"database"}
      KEYSTONE_DB_USER: ${KEYSTONE_DB_USER:-keystone}
      KEYSTONE_DB_NAME: ${KEYSTONE_DB_NAME:-keystone}
      KEYSTONE_DEBUG: ${KEYSTONE_DEBUG:-"false"}
      HTTP: ${HTTP:-http}
    ports:
      - "5000:5000"
      - "35357:35357"

  database:
    container_name: keystone-database
    image: mariadb:10.4.5-bionic
    networks:
      - keystone-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARKET_DB_PASSWORD: ${MARKET_DB_PASSWORD}
      PROVIDER_DB_PASSWORD: ${PROVIDER_DB_PASSWORD}
      MYSQL_USER: ${KEYSTONE_DB_USER:-keystone}
      MYSQL_PASSWORD: ${KEYSTONE_DB_PASSWORD}
      MYSQL_DATABASE: ${KEYSTONE_DB_NAME:-keystone}


  mongodb:
    container_name: mongodb
    image: mongo:3.6
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"


  everyboss:
    container_name: everyboss
    image: ghcr.io/cscarpitta/everyboss:latest
    network_mode: "host"


  everyedgeos:
    container_name: everyedgeos
    image: ghcr.io/cscarpitta/everyedgeos:latest
    network_mode: "host"
    cap_add:
       - NET_ADMIN


  everygui:
    container_name: everygui
    image: ghcr.io/cscarpitta/everygui:latest
    network_mode: "host"


networks:
  keystone-net:
  nbi-net: