# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image (EveryWAN Virtual Network)

on:
  push:
    branches: ['master']
    paths:
      - 'VirtualNet/VERSION'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: cscarpitta/everywan-virtualnet

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current version
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ./VirtualNet/VERSION

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
              type=semver,pattern={{version}},value=${{ steps.read_file.outputs.contents }}
              type=semver,pattern={{major}}.{{minor}},value=${{ steps.read_file.outputs.contents }}
              type=semver,pattern={{major}},value=${{ steps.read_file.outputs.contents }}
              type=sha

      - name: Build and push Docker image (EveryWAN Virtual Network)
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./VirtualNet
          push: true
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=registry,dest=everywan-virtualnet
